/**
 * IPC Channels - Channel definitions and validators
 */

import { IPC_CHANNELS } from './protocol';

/**
 * Main process channels (renderer -> main)
 */
export const MAIN_CHANNELS = [
  // Agent
  IPC_CHANNELS.AGENT_START,
  IPC_CHANNELS.AGENT_STOP,
  IPC_CHANNELS.AGENT_STATUS,
  IPC_CHANNELS.AGENT_PROMPT,
  IPC_CHANNELS.AGENT_ABORT,
  IPC_CHANNELS.AGENT_TEST_CONNECTION,
  // Chat
  IPC_CHANNELS.CHAT_SEND,
  IPC_CHANNELS.CHAT_STREAM,
  IPC_CHANNELS.CHAT_STOP,
  IPC_CHANNELS.CHAT_CLEAR,
  IPC_CHANNELS.CHAT_NEW,
  // Sessions
  IPC_CHANNELS.SESSION_NEW,
  IPC_CHANNELS.SESSION_LIST,
  IPC_CHANNELS.SESSION_GET,
  IPC_CHANNELS.SESSION_DELETE,
  IPC_CHANNELS.SESSION_RENAME,
  // Settings
  IPC_CHANNELS.SETTINGS_GET,
  IPC_CHANNELS.SETTINGS_UPDATE,
  IPC_CHANNELS.SETTINGS_RESET,
  IPC_CHANNELS.SETTINGS_SAVE,
  IPC_CHANNELS.SETTINGS_REFRESH_AUTH_BACKEND,
  // Billing
  IPC_CHANNELS.BILLING_STATUS,
  IPC_CHANNELS.BILLING_USAGE,
  IPC_CHANNELS.BILLING_SUBSCRIBE,
  // Plugin Channel
  IPC_CHANNELS.CHANNEL_PLUGIN_LIST,
  IPC_CHANNELS.CHANNEL_PLUGIN_INSTALL,
  IPC_CHANNELS.CHANNEL_PLUGIN_UNINSTALL,
  IPC_CHANNELS.CHANNEL_PLUGIN_CONFIG,
  IPC_CHANNELS.CHANNEL_PLUGIN_LOGIN,
  // Channel management
  IPC_CHANNELS.CHANNEL_LIST,
  IPC_CHANNELS.CHANNEL_SET_MAIN,
  IPC_CHANNELS.CHANNEL_LOGIN,
  IPC_CHANNELS.CHANNEL_DISCONNECT,
  // Work queue
  IPC_CHANNELS.WORK_COMPLETE,
  IPC_CHANNELS.WORK_DELETE,
  // File management (already have UPLOAD/DELETE, adding)
  IPC_CHANNELS.FILE_UPLOAD,
  IPC_CHANNELS.FILE_DELETE,
  // ColaLink
  IPC_CHANNELS.COLALINK_PROFILE_GET,
  IPC_CHANNELS.COLALINK_PROFILE_UPDATE,
  IPC_CHANNELS.COLALINK_CONTACTS_LIST,
  IPC_CHANNELS.COLALINK_CONTACTS_ADD,
  IPC_CHANNELS.COLALINK_CONTACTS_DELETE,
  IPC_CHANNELS.COLALINK_CONTACTS_BLOCK,
  IPC_CHANNELS.COLALINK_MESSAGE_SEND,
  IPC_CHANNELS.COLALINK_MESSAGE_HISTORY,
  IPC_CHANNELS.COLALINK_RELAY_CONNECT,
  IPC_CHANNELS.COLALINK_RELAY_DISCONNECT,
  // Speech
  IPC_CHANNELS.HOST_STT_CREATE_STREAM,
  IPC_CHANNELS.HOST_STT_PUSH,
  IPC_CHANNELS.HOST_STT_FINISH,
  IPC_CHANNELS.HOST_STT_CANCEL,
  IPC_CHANNELS.HOST_TTS_SYNTHESIZE,
  // Settings misc
  IPC_CHANNELS.SETTINGS_BLOCKED_PATHS_CHANGED,
  // Model
  IPC_CHANNELS.MODEL_SET_TIER,
  // Window
  IPC_CHANNELS.WINDOW_TRAFFIC_LIGHTS,
  // Auth
  IPC_CHANNELS.AUTH_GET,
  IPC_CHANNELS.AUTH_REFRESH,
  IPC_CHANNELS.AUTH_SET_TOKENS,
  IPC_CHANNELS.AUTH_LOGOUT,
  // Models & Skills
  IPC_CHANNELS.MODELS_LIST,
  IPC_CHANNELS.MODELS_SWITCH,
  IPC_CHANNELS.MODEL_SET,
  IPC_CHANNELS.SKILLS_LIST,
  IPC_CHANNELS.SKILLS_ENABLE,
  IPC_CHANNELS.SKILLS_DISABLE,
  IPC_CHANNELS.SKILL_SET_ENABLED,
  // Modes
  IPC_CHANNELS.MOD_LIST,
  IPC_CHANNELS.MOD_SWITCH,
  IPC_CHANNELS.MOD_CURRENT,
  // Files
  IPC_CHANNELS.FILE_UPLOAD,
  IPC_CHANNELS.FILE_DELETE,
  // Onboarding
  IPC_CHANNELS.ONBOARDING_GET_STATUS,
  IPC_CHANNELS.ONBOARDING_GET_PROGRESS,
  IPC_CHANNELS.ONBOARDING_NEXT_STEP,
  IPC_CHANNELS.ONBOARDING_SKIP_STEP,
  IPC_CHANNELS.ONBOARDING_VALIDATE_API_KEY,
  IPC_CHANNELS.ONBOARDING_SAVE_API_KEY,
  IPC_CHANNELS.ONBOARDING_SAVE_MODEL,
  IPC_CHANNELS.ONBOARDING_COMPLETE,
  IPC_CHANNELS.ONBOARDING_SKIP,
  IPC_CHANNELS.ONBOARDING_RESET,
  // Search
  IPC_CHANNELS.SEARCH_CONVERSATIONS,
  IPC_CHANNELS.SEARCH_SUGGESTIONS,
  IPC_CHANNELS.SEARCH_INDEX,
  IPC_CHANNELS.SEARCH_HISTORY,
  // Mini Window
  IPC_CHANNELS.MINI_WINDOW_SHOW,
  IPC_CHANNELS.MINI_WINDOW_HIDE,
  IPC_CHANNELS.MINI_WINDOW_TOGGLE,
  IPC_CHANNELS.MINI_WINDOW_SEND_MESSAGE,
  IPC_CHANNELS.MINI_CHAT_SHORTCUT_REGISTER,
  IPC_CHANNELS.MINI_CHAT_SHORTCUT_GET_STATUS,
  // Window management
  IPC_CHANNELS.WINDOW_SHOW_MAIN,
  IPC_CHANNELS.WINDOW_MINIMIZE,
  IPC_CHANNELS.WINDOW_HIDE,
  // Diagnostics
  IPC_CHANNELS.DIAGNOSTICS_NETWORK,
  IPC_CHANNELS.DIAGNOSTICS_UPDATER,
  // Storage
  IPC_CHANNELS.STORAGE_GET,
  IPC_CHANNELS.STORAGE_SET,
  IPC_CHANNELS.STORAGE_DELETE,
  // OAuth
  IPC_CHANNELS.OAUTH_LOGIN,
  IPC_CHANNELS.OAUTH_RESPOND,
  IPC_CHANNELS.OAUTH_CANCEL,
  // Permissions
  IPC_CHANNELS.PERMISSION_REQUEST,
  IPC_CHANNELS.PERMISSION_PATH_REQUEST,
  IPC_CHANNELS.PERMISSION_RESPOND,
  IPC_CHANNELS.PERMISSION_CANCEL,
  // Work Queue
  IPC_CHANNELS.QUEUE_LIST,
  IPC_CHANNELS.QUEUE_ADD,
  IPC_CHANNELS.QUEUE_REMOVE,
  // Scheduled Tasks
  IPC_CHANNELS.CRON_LIST,
  IPC_CHANNELS.CRON_DELETE,
  IPC_CHANNELS.CRON_SET_ENABLED,
  // Notifications
  IPC_CHANNELS.NOTIFICATION_LIST,
  IPC_CHANNELS.NOTIFICATION_DISMISS,
  IPC_CHANNELS.NOTIFICATION_CLEAR,
  // Themes
  IPC_CHANNELS.THEMES_LOAD,
  IPC_CHANNELS.THEMES_SAVE,
] as const;

/**
 * Renderer channels (main -> renderer)
 */
export const RENDERER_CHANNELS = [
  IPC_CHANNELS.EVENT_MESSAGE,
  IPC_CHANNELS.EVENT_STREAM_CHUNK,
  IPC_CHANNELS.EVENT_STREAM_END,
  IPC_CHANNELS.EVENT_ERROR,
  IPC_CHANNELS.EVENT_STATUS_CHANGE
] as const;

/**
 * Check if channel is valid main channel
 */
export function isValidMainChannel(channel: string): boolean {
  return MAIN_CHANNELS.includes(channel as any);
}

/**
 * Check if channel is valid renderer channel
 */
export function isValidRendererChannel(channel: string): boolean {
  return RENDERER_CHANNELS.includes(channel as any);
}

/**
 * Get channel category
 */
export function getChannelCategory(channel: string): string {
  const parts = channel.split(':');
  return parts[0] || 'unknown';
}

/**
 * Check if channel requires authentication
 */
export function requiresAuth(channel: string): boolean {
  // All channels except status check require authentication
  return channel !== IPC_CHANNELS.AGENT_STATUS;
}
